Add Windows CMake add_subdirectory for modules

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -344,129 +344,129 @@ jobs:
   #         cmake --build .
   #         ctest --output-on-failure --no-tests=error
 
-  posix-cmake-install:
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          # - os: ubuntu-20.04
-          # - os: ubuntu-22.04
-          # - os: ubuntu-24.04
-          - os: ubuntu-24.04
-            container: ubuntu:24.10
-            cmake-args: -DBOOST_USE_MODULES=1 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -DCMAKE_CXX_STANDARD=23 -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=0e5b6991-d74f-4b3d-a41c-cf096e0b2508 -G Ninja
-            install: ninja-build cmake clang-19 llvm-19 libclang-rt-19-dev libc++-19-dev libc++abi-19-dev clang-tools-19 git ca-certificates python3 python-is-python3
-          # - os: macos-13
-          # - os: macos-14
-          # - os: macos-15
+  # posix-cmake-install:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - os: ubuntu-20.04
+  #         - os: ubuntu-22.04
+  #         - os: ubuntu-24.04
+  #         - os: ubuntu-24.04
+  #           container: ubuntu:24.10
+  #           cmake-args: -DBOOST_USE_MODULES=1 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -DCMAKE_CXX_STANDARD=23 -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=0e5b6991-d74f-4b3d-a41c-cf096e0b2508 -G Ninja
+  #           install: ninja-build cmake clang-19 llvm-19 libclang-rt-19-dev libc++-19-dev libc++abi-19-dev clang-tools-19 git ca-certificates python3 python-is-python3
+  #         - os: macos-13
+  #         - os: macos-14
+  #         - os: macos-15
 
-    runs-on: ${{matrix.os}}
-    container: ${{matrix.container}}
+  #   runs-on: ${{matrix.os}}
+  #   container: ${{matrix.container}}
 
-    steps:
-      - uses: actions/checkout@v4
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Install packages
-        if: matrix.install
-        run: export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --no-install-recommends ${{matrix.install}}
+  #     - name: Install packages
+  #       if: matrix.install
+  #       run: export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --no-install-recommends ${{matrix.install}}
 
-      - name: Setup Boost
-        run: |
-          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
-          LIBRARY=${GITHUB_REPOSITORY#*/}
-          echo LIBRARY: $LIBRARY
-          echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
-          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
-          echo GITHUB_REF: $GITHUB_REF
-          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
-          REF=${REF#refs/heads/}
-          echo REF: $REF
-          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
-          echo BOOST_BRANCH: $BOOST_BRANCH
-          cd ..
-          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
-          cd boost-root
-          cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
-          python libs/mp11/tools/setup_boost_with_modules.py # Temporary
+  #     - name: Setup Boost
+  #       run: |
+  #         echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
+  #         LIBRARY=${GITHUB_REPOSITORY#*/}
+  #         echo LIBRARY: $LIBRARY
+  #         echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
+  #         echo GITHUB_BASE_REF: $GITHUB_BASE_REF
+  #         echo GITHUB_REF: $GITHUB_REF
+  #         REF=${GITHUB_BASE_REF:-$GITHUB_REF}
+  #         REF=${REF#refs/heads/}
+  #         echo REF: $REF
+  #         BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
+  #         echo BOOST_BRANCH: $BOOST_BRANCH
+  #         cd ..
+  #         git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
+  #         cd boost-root
+  #         cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
+  #         python libs/mp11/tools/setup_boost_with_modules.py # Temporary
 
-      - name: Configure
-        run: |
-          cd ../boost-root
-          mkdir __build__ && cd __build__
-          cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DCMAKE_INSTALL_PREFIX=~/.local ${{ matrix.cmake-args }} ..
+  #     - name: Configure
+  #       run: |
+  #         cd ../boost-root
+  #         mkdir __build__ && cd __build__
+  #         cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DCMAKE_INSTALL_PREFIX=~/.local ${{ matrix.cmake-args }} ..
 
-      - name: Install
-        run: |
-          cd ../boost-root/__build__
-          cmake --build . --target install
+  #     - name: Install
+  #       run: |
+  #         cd ../boost-root/__build__
+  #         cmake --build . --target install
 
-      - name: Use the installed library
-        run: |
-          cd ../boost-root/libs/$LIBRARY/test/cmake_install_test && mkdir __build__ && cd __build__
-          cmake -DCMAKE_INSTALL_PREFIX=~/.local ${{ matrix.cmake-args }} ..
-          cmake --build .
-          ctest --output-on-failure --no-tests=error
+  #     - name: Use the installed library
+  #       run: |
+  #         cd ../boost-root/libs/$LIBRARY/test/cmake_install_test && mkdir __build__ && cd __build__
+  #         cmake -DCMAKE_INSTALL_PREFIX=~/.local ${{ matrix.cmake-args }} ..
+  #         cmake --build .
+  #         ctest --output-on-failure --no-tests=error
 
-  posix-cmake-test:
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          # - os: ubuntu-20.04
-          # - os: ubuntu-22.04
-          # - os: ubuntu-24.04
-          - os: ubuntu-24.04
-            container: ubuntu:24.10
-            cmake-args: -DBOOST_USE_MODULES=1 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -DCMAKE_CXX_STANDARD=23 -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=0e5b6991-d74f-4b3d-a41c-cf096e0b2508 -G Ninja
-            install: ninja-build cmake clang-19 llvm-19 libclang-rt-19-dev libc++-19-dev libc++abi-19-dev clang-tools-19 git ca-certificates python3 python-is-python3
-          # - os: macos-13
-          # - os: macos-14
-          # - os: macos-15
+  # posix-cmake-test:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - os: ubuntu-20.04
+  #         - os: ubuntu-22.04
+  #         - os: ubuntu-24.04
+  #         - os: ubuntu-24.04
+  #           container: ubuntu:24.10
+  #           cmake-args: -DBOOST_USE_MODULES=1 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -DCMAKE_CXX_STANDARD=23 -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=0e5b6991-d74f-4b3d-a41c-cf096e0b2508 -G Ninja
+  #           install: ninja-build cmake clang-19 llvm-19 libclang-rt-19-dev libc++-19-dev libc++abi-19-dev clang-tools-19 git ca-certificates python3 python-is-python3
+  #         - os: macos-13
+  #         - os: macos-14
+  #         - os: macos-15
 
-    runs-on: ${{matrix.os}}
-    container: ${{matrix.container}}
+  #   runs-on: ${{matrix.os}}
+  #   container: ${{matrix.container}}
 
-    steps:
-      - uses: actions/checkout@v4
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Install packages
-        if: matrix.install
-        run: export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --no-install-recommends ${{matrix.install}}
+  #     - name: Install packages
+  #       if: matrix.install
+  #       run: export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --no-install-recommends ${{matrix.install}}
 
-      - name: Setup Boost
-        run: |
-          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
-          LIBRARY=${GITHUB_REPOSITORY#*/}
-          echo LIBRARY: $LIBRARY
-          echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
-          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
-          echo GITHUB_REF: $GITHUB_REF
-          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
-          REF=${REF#refs/heads/}
-          echo REF: $REF
-          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
-          echo BOOST_BRANCH: $BOOST_BRANCH
-          cd ..
-          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
-          cd boost-root
-          cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
-          python3 libs/mp11/tools/setup_boost_with_modules.py # Temporary
+  #     - name: Setup Boost
+  #       run: |
+  #         echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
+  #         LIBRARY=${GITHUB_REPOSITORY#*/}
+  #         echo LIBRARY: $LIBRARY
+  #         echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
+  #         echo GITHUB_BASE_REF: $GITHUB_BASE_REF
+  #         echo GITHUB_REF: $GITHUB_REF
+  #         REF=${GITHUB_BASE_REF:-$GITHUB_REF}
+  #         REF=${REF#refs/heads/}
+  #         echo REF: $REF
+  #         BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
+  #         echo BOOST_BRANCH: $BOOST_BRANCH
+  #         cd ..
+  #         git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
+  #         cd boost-root
+  #         cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
+  #         python3 libs/mp11/tools/setup_boost_with_modules.py # Temporary
 
-      - name: Configure
-        run: |
-          cd ../boost-root
-          mkdir __build__ && cd __build__
-          cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DBUILD_TESTING=ON ${{ matrix.cmake-args }} ..
+  #     - name: Configure
+  #       run: |
+  #         cd ../boost-root
+  #         mkdir __build__ && cd __build__
+  #         cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DBUILD_TESTING=ON ${{ matrix.cmake-args }} ..
 
-      - name: Build tests
-        run: |
-          cd ../boost-root/__build__
-          cmake --build . --target tests
+  #     - name: Build tests
+  #       run: |
+  #         cd ../boost-root/__build__
+  #         cmake --build . --target tests
 
-      - name: Run tests
-        run: |
-          cd ../boost-root/__build__
-          ctest --output-on-failure --no-tests=error
+  #     - name: Run tests
+  #       run: |
+  #         cd ../boost-root/__build__
+  #         ctest --output-on-failure --no-tests=error
 
   # standalone-cmake-subdir:
   #   strategy:
@@ -813,3 +813,48 @@ jobs:
   #       run: |
   #         cd ../boost-root/__build__
   #         ctest --output-on-failure --no-tests=error -C Release
+
+  windows-cmake-subdir-modules:
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - cmake-build-type: Debug
+          - cmake-build-type: Release
+
+    runs-on: windows-2022
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install packages
+        if: matrix.install
+        run: choco install ninja
+
+      - name: Setup Boost
+        shell: cmd
+        run: |
+          echo GITHUB_REPOSITORY: %GITHUB_REPOSITORY%
+          for /f %%i in ("%GITHUB_REPOSITORY%") do set LIBRARY=%%~nxi
+          echo LIBRARY: %LIBRARY%
+          echo LIBRARY=%LIBRARY%>>%GITHUB_ENV%
+          echo GITHUB_BASE_REF: %GITHUB_BASE_REF%
+          echo GITHUB_REF: %GITHUB_REF%
+          if "%GITHUB_BASE_REF%" == "" set GITHUB_BASE_REF=%GITHUB_REF%
+          set BOOST_BRANCH=develop
+          for /f %%i in ("%GITHUB_BASE_REF%") do if "%%~nxi" == "master" set BOOST_BRANCH=master
+          echo BOOST_BRANCH: %BOOST_BRANCH%
+          cd ..
+          git clone -b %BOOST_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
+          cd boost-root
+          xcopy /s /e /q %GITHUB_WORKSPACE% libs\%LIBRARY%\
+          python libs/mp11/tools/setup_boost_with_modules.py # Temporary
+
+      - name: Use library with add_subdirectory
+        shell: cmd
+        run: |
+          cd ../boost-root/libs/%LIBRARY%/test/cmake_subdir_test
+          mkdir __build__ && cd __build__
+          cmake -DBOOST_USE_MODULES=1 -DCMAKE_CXX_STANDARD=23 -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD=0e5b6991-d74f-4b3d-a41c-cf096e0b2508 -DCMAKE_BUILD_TYPE=${{cmake-build-type}} -G Ninja ..
+          cmake --build .
+          ctest --output-on-failure --no-tests=error
